name: Automerge

on:
  check_suite:
    types:
      - completed

  pull_request_review:
    types:
      - submitted

  pull_request_target:
    types:
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          squash-title: true
          dry-run: false
