# This is a basic workflow to help you get started with Actions

name: Test Site

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Sphinx Build
        uses: ammaraskar/sphinx-action@0.4
        with:
          pre-build-command: "apt-get install -y git"
          docs-folder: '.'
          build-command: "sphinx-build -aE -W -b dirhtml source build"
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: PREVIEW/${{GITHUB_HEAD_REF}}
          keep_files: true
          cname: vpfig.com
