# This is a basic workflow to help you get started with Actions

name: Test Site

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Sphinx Build
        uses: ammaraskar/sphinx-action@0.4
        with:
          pre-build-command: "apt-get install -y git"
          docs-folder: '.'
          build-command: "sphinx-build -aE -W -b dirhtml source build"
      
      - name: Build and deploy to gh-pages
        uses: sauloxd/review-apps@v1.3.3
        with:
          build-cmd: 'sphinx-build -aE -b dirhtml source build'
          branch: 'gh-pages' # The branch you chose to be your github-pages source
          dist: 'build' # The dist folder where your build command will place the build artifacts
          slug: 'PREVIEW' # The partial URL where your apps will live. This is useful if you want to deploy both your react app and storybook app inside the same repository

